- name: uninstall ntpd
  apt: name=ntp state=absent purge=yes

- name: remove obsolete ntpd configuration
  file: dest="{{ item }}" state=absent
  with_items:
    - /etc/ntp.conf
    - /etc/default/ntpd

# OpenNTPD does not listen by default and is hence easier to configure
# (as in: comes configured securely)
- name: install OpenNTPD
  package: name=openntpd state=present
  when: ansible_virtualization_type != "lxc"

# service module does not work on all hosts currently (16/06)!?
- name: ensure OpenNTPD is started
  command: service openntpd start

# service module does not work on all hosts currently (16/06)!?
- name: ensure OpenNTPD starts at boot
  command: update-rc.d openntpd enable
