- name: install arpwatch
  package: name=arpwatch state=present
  when: arpwatch_enabled

- name: uninstall arpwatch
  package: name=arpwatch state=absent
  when: not arpwatch_enabled

- name: enable & start arpwatch
  service: name=arpwatch enabled=yes state=started
  when: arpwatch_enabled

- name: disable USB storage
  kernel_blacklist: name=usb-storage state=present
  when: not needs_usb_storage

- name: disable FireWire storage (and maybe more)
  kernel_blacklist: name="{{ item }}" state=present
  with_items:
    - firewire-ohci
    - firewire-sbp2
  when: not needs_firewire_storage
