- name: add configuration files for sysctl (kernel parameters)
  file: src="/opt/admintools/etc/sysctl.d/{{ item }}"
        dest="/etc/sysctl.d/{{ item }}"
        state=link
  with_items:
    - 90-hardening.conf
    - 80-net-tuning.conf
    - 50-reboot-on-panic.conf
  notify: sysctl reload

- name: add hotfix for CVE-2016-5696 for vulnerable Kernels
  file: src=/opt/admintools/etc/sysctl.d/CVE-2016-5696.conf
        dest=/etc/sysctl.d/CVE-2016-5696.conf
        state=link
  when: ansible_kernel | version_compare('4.7', '<')
  notify: sysctl reload

- name: disable hotfix for CVE-2016-5696 for patched Kernels
  file: dest=/etc/sysctl.d/CVE-2016-5696.conf
        state=absent
  when: ansible_kernel | version_compare('4.7', '>=')
  notify: sysctl reload
