- name: provide default configuration
  copy: src=tahoe-default.cfg
        dest="{{ tahoe_basedir }}/node/tahoe.cfg"
        force=no
  notify: restart node

- name: set node nickname
  ini_file: dest="{{ tahoe_basedir }}/node/tahoe.cfg"
            section=node
            option=nickname
            value='{{ ansible_nodename|default(ansible_fqdn) }}'
  notify: restart node

- name: set global furls
  ini_file: dest="{{ tahoe_basedir }}/node/tahoe.cfg"
            section="{{ item.section }}"
            option="{{ item.option }}"
            value="{{ item.value }}"
  when: item is not undefined
  with_items:
    - section: node
      option: introducer.furl
      value: "{{ tahoe_introducer_furl|default(None) }}"
    - section: node
      option: log_gatherer.furl
      value: "{{ tahoe_log_gatherer_furl|default(None) }}"
    - section: client
      option: stats_gatherer.furl
      value: "{{ tahoe_stats_gatherer_furl|default(None) }}"
  notify: restart node

- name: set keepalive
  ini_file: dest="{{ tahoe_basedir }}/node/tahoe.cfg"
            section=node
            option=timeout.keepalive
            value=60
  notify: restart node

- name: set default mutable format
  ini_file: dest="{{ tahoe_basedir }}/node/tahoe.cfg"
            section=client
            option=mutable.format
            value=mdmf
  notify: restart node

############################ encoding ############################

- name: set encoding parameter shares.total
  ini_file: dest="{{ tahoe_basedir }}/node/tahoe.cfg"
            section=client
            option=shares.total
            value="{{tahoe_shares_total}}"
  notify: restart node

- name: set encoding parameter shares.happy
  ini_file: dest="{{ tahoe_basedir }}/node/tahoe.cfg"
            section=client
            option=shares.happy
            value="{{tahoe_shares_happy}}"
  notify: restart node

- name: set encoding parameter shares.needed
  ini_file: dest="{{ tahoe_basedir }}/node/tahoe.cfg"
            section=client
            option=shares.needed
            value="{{tahoe_shares_needed}}"
  notify: restart node
