- name: check return code of '{{ fail2ban_jail_auto_enable.value }}'
  register: check_command_result
  shell: "{{ fail2ban_jail_auto_enable.value }}"
  changed_when: false
  failed_when: false

- name: "{{ 'enable' if check_command_result.rc == 0 else 'disable'}}
         jail '{{ fail2ban_jail_auto_enable.key }}'"
  ini_file:
    path: "{{ fail2ban_jails_config_file }}"
    section: "{{ fail2ban_jail_auto_enable.key }}"
    option: enabled
    value: true
    state: "{{ 'present' if check_command_result.rc == 0 else 'absent'}}"
  notify: reload fail2ban
