#
# OSI layer 7 firewall is currently Fail2ban.
# This file takes care of Fail2ban's configuration.
#

# we use the apt package, so we can ``install_recommends``
- name: install Fail2ban
  apt:
    name: fail2ban
    state: present
    install_recommends: yes

- name: load kernel module for ip_tables
  register: modprobe_iptables_result
  modprobe:
    name: ip_tables
    state: present
  notify: reload fail2ban

- name: ensure kernel module for ip_tables is loaded at boot
  lineinfile:
    path: /etc/modules
    line: ip_tables
    regexp: '^ip_tables(\s.*)?'
    create: yes
  when: modprobe_iptables_result.changed

- name: enable and start fail2ban
  service:
    name: fail2ban
    enabled: true
    state: started

- name: processing Fail2ban jails to automatically enable/disable
  include_tasks: _fail2ban-auto-enable-jail.yml
  with_dict: "{{ fail2ban_jails_auto_enable |
                 combine(fail2ban_jails_extra_auto_enable | default({})) }}"
  loop_control:
    loop_var: fail2ban_jail_auto_enable

- name: processing static Fail2ban jail configuration
  include_tasks: _fail2ban-write-config-section.yml
  with_dict: "{{ fail2ban_jails_config |
                 combine(fail2ban_jails_extra_config | default({})) }}"
  loop_control:
    loop_var: section
