- name: "get range of {{ item }}s to add"
  register: get_range_result
  shell: "grep '{{ lxc_user }}' '/etc/{{ item }}'
          | cut -d: -f 2-3"
  changed_when: false

- name: "sanity check detected range of {{ item }}s"
  assert:
    that:
      - "get_range_result.stdout_lines | length == 1"
      - "get_range_result.stdout_lines.0 | regex_search('[0-9]+:[0-9]+')
         ==
         get_range_result.stdout_lines.0"
    fail_msg: "could not detect {{ item }}s to add to {{ lxc_user }}
               (expected exactly one range,
                got '{{ get_range_result.stdout_lines }}')"

- name: "add {{ item }}s to common lxc configuration of user '{{ lxc_user }}'"
  lineinfile:
    dest: "{{ lxc_user_home }}/.config/lxc/common.conf"
    create: yes
    regexp: '^\s*lxc\.idmap\s*=\s*{{ item.3 }}'
    line: "lxc.idmap = {{ item.3 }} 0 {{
      get_range_result.stdout_lines.0 | regex_replace(':', ' ')
    }}"
  become: yes
  become_user: "{{ lxc_user }}"
