lxc_user: lxc

lxc_create_args_extra: ''

# Default values for nested dictionaries of ``lxc_containers``.
lxc_container_defaults:
  create_args: >
    {{ lxc_create_args_extra | default('') }}
    --template download -- --dist debian --release buster --arch amd64

# you can use this variable to override individual keys in
# ``lxc_container_defaults``
lxc_container_defaults_extra: {}

# Dictionary (of dictionaries) defining the containers to set up.
# The **keys** are the container names,
# the **values** the containers' properties.
# The following keys are required/supported for the nested dictionaries:
#   name (required): name of the container
#   subnet (required): IPv6 subnet for the container (e.g., "fd01::/16")
lxc_containers:

  # /!\ TODO: my config, move away from role defaults

  rproxy:
    subnet: "fd00::/16"

  #~ drop:
    #~ subnet: "fd01::/16"

  test:
    subnet: "fdff::/16"

# /!\ will be deleted permanently, including configuration, network, etc.
lxc_containers_to_delete_permanently:

  - test
