php_global_options:

  # Example: How to add custom PHP options
  #          (put this into your Playbook vars):
  #  - php_extra_options:
  #    upload_max_filesize: 20M

  allow_url_fopen: "Off"
  allow_url_include: "Off"
  register_globals: "Off"
  display_errors: "Off"
  disable_functions:  php_uname,
                      getmyuid,
                      getmypid,
                      passthru,
                      leak,
                      listen,
                      diskfreespace,
                      tmpfile,
                      link,
                      ignore_user_abord,
                      shell_exec,
                      dl,
                      set_time_limit,
                      exec,
                      system,
                      highlight_file,
                      source,
                      show_source,
                      fpaththru,
                      virtual,
                      posix_ctermid,
                      posix_getcwd,
                      posix_getegid,
                      posix_geteuid,
                      posix_getgid,
                      posix_getgrgid,
                      posix_getgrnam,
                      posix_getgroups,
                      posix_getlogin,
                      posix_getpgid,
                      posix_getpgrp,
                      posix_getpid,
                      posix,
                      _getppid,
                      posix_getpwnam,
                      posix_getpwuid,
                      posix_getrlimit,
                      posix_getsid,
                      posix_getuid,
                      posix_isatty,
                      posix_kill,
                      posix_mkfifo,
                      posix_setegid,
                      posix_seteuid,
                      posix_setgid,
                      posix_setpgid,
                      posix_setsid,
                      posix_setuid,
                      posix_times,
                      posix_ttyname,
                      posix_uname,
                      proc_open,
                      proc_close,
                      proc_get_status,
                      proc_nice,
                      proc_terminate,
                      phpinfo
